# $File: //ASP/opa/mct/iocs/MCTDEVIOC06/MCTDEVIOC06App/Makefile $
# $Revision: #1 $
# $DateTime: 2022/06/24 04:29:50 $
# Last checked in by: $Author: lewisw $
#

TOP = ..
include $(TOP)/configure/CONFIG
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *db*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Db*))
include $(TOP)/configure/RULES_DIRS

# end
