# $File: //ASP/opa/mct/iocs/MCTDEVIOC06/MCTDEVIOC06App/Db/Makefile $
# $Revision: #2 $
# $DateTime: 2022/06/24 05:00:02 $
# Last checked in by: $Author: lewisw $
#

TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += MCTVBM01_position_status.db  
#
#CRAPI += vbm_stripe_control.req

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


# end
